stages:
  - build
#  - deploy

variables:
  IMAGE_NAME: "benmiblog"
  IMAGE_TAG: "latest"
  PODMAN_REGISTRY: "registry.gitlab.com"

build:
  stage: build
  image: quay.io/podman/stable
  script:
    - podman build -t ${PODMAN_REGISTRY}/${CI_PROJECT_PATH}:${IMAGE_TAG} .
#    - podman push ${PODMAN_REGISTRY}/${CI_PROJECT_PATH}:${IMAGE_TAG}

#deploy:
#  stage: deploy
#  script:
#    - echo "Deploying ${PODMAN_REGISTRY}/${CI_PROJECT_PATH}:${IMAGE_TAG}"
#    # Add your deployment steps here
